name: Build Sarmap Library

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install gcc

    - name: Compile Libraries
      run: make all

    - name: Run Tests
      env:
        LD_LIBRARY_PATH: ${{ github.workspace }}/lib
      run: ./bin/main || { echo "Tests failed"; exit 1; }
