name: Build Sarmap Library

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC and GDB
      run: sudo apt-get install gcc gdb

    - name: Compile Libraries
      run: make all

    - name: Run Tests
      env:
        LD_LIBRARY_PATH: ${{ github.workspace }}/lib
      run: |
        gdb -batch -ex "run" -ex "bt" ./bin/main
